### ISSUE TITLE
Various modal form issues

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#314] opened 2022-10-13 13:29 UTC
Version: testing_pkg_fabrik_4.0alpha1 tested on plain J4 / F4
- on mouseover, a validation icon (eye) shows html code <ul class = "validation-notices" etc (tested using NotEmpty)
- validation Error message is not shown (tested using NotEmpty)
- after using the Delete button, the form does not close still showing the record. After closing manually, the list is not updated automatically and still shows the deleted record. Clicking it shows an empty record. I believe F3 has this bug too.
- the jdate element datepicker pop-up is not shown

**Comment by joomlahenk** [comment] 2022-10-13 17:27
I could not reproduce "validation icon (eye) shows html code" issue. Is working OK on my site, also shows validation message.
Delete button (on the form) works on my site. Is also closing the form and record is deleted as shown in the list.
Jdate is showing datepicker pop-up on my site also.

I have a 'virgin' joomla 4.2.3 & PHP8.1. with the fabrik4.0alpha1 installed.
I created a default list 'test' with id, jdate and field and added textarea, calc and jdate elements
Did not change any config settings in joomla and fabrik.

Can you add more info of how to reproduce the issue(s)?

**Comment by EricdeWaal** [comment] 2022-10-14 07:37
I have a 'virgin' joomla 4.2.2 site, updated to 4.2.3, No other extensions, just fabrik4.0alpha1. PHP is 8.1.11. Above problems **only occurr in a modal (pop-up) form**. The browser is Firefox on Windows 10, and Edge behaves identical.

My list is very similar to yours. 

- On mouseover of the eye icon I do not get the black pop-up but the html text in a white bordered box, see screenshot 

![screenshot-modal](https://user-images.githubusercontent.com/5586423/195788255-95226bc5-c7b1-4d5e-bd7a-c2b042b6f18c.jpg)

- The Delete button issue solved itself!
- on clicking the jdate blue button, no calendar is shown (works in non-modal forms)
- the validation Error message is not shown, see screenshot 2 (also works in non-modal forms)

![screenshot-modal-2](https://user-images.githubusercontent.com/5586423/195789663-38029661-2c94-436e-a0ac-d4f2c52d6f8d.jpg)

**Comment by joomlahenk** [comment] 2022-10-14 11:44
OK, now I can reproduce. Only occurs if Ajaxify links is set to yes.

**Comment by joomlahenk** [comment] 2022-10-14 19:57
Issue item 1 & 2 solved, see #325. Other items still to solve

**Comment by joomlahenk** [comment] 2022-10-14 20:11
I will create separate issues for item 3 and 4 and then close this issue.

**Closed by joomlahenk** 2022-10-14 20:11 UTC
Labels: Medium Priority
