### ISSUE TITLE
Content plugin parameter

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#571] opened 2022-11-28 14:03 UTC
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Call a form from an article and try to pass a parameter to fill a field
eg {fabrik view=form id=6 b_liste___text=2}

**Expected behavior**
Field b_liste___text has the value 2

**Actual behavior**
Field b_liste___text is empty

**Screenshots**

**Additional context**

**Comment by trob** [comment] 2022-11-29 10:37
List filtering is working with content plugin 'element' parameter.
Other params like show-title=0 are working, too.
So it seems to be an issue with element default setting not fetching this param.

**Comment by wezetel** [comment] 2022-11-29 20:26
Does this mean, it is specific for specific element types? I'm using a standard field.

**Comment by skurvish** [comment] 2022-12-10 15:39
@wezetel can you try unzipping this into your joomla root and report if the problem is solved? Thanks.
[cumulative_12_10_2022.zip](https://github.com/joomlahenk/fabrik/files/10200379/cumulative_12_10_2022.zip)

**Comment by trob** [comment] 2022-12-10 16:20
Seems it needs both : $_GET for params in list view and $_REQUEST for form view

**Comment by skurvish** [comment] 2022-12-10 16:27
OK, I will reinsert the get so they will both be there. @wezetel please try with this cumulative, it includes the change requested by @trob 
[cumulative_12_10_2022.zip](https://github.com/joomlahenk/fabrik/files/10200459/cumulative_12_10_2022.zip)

**Comment by wezetel** [comment] 2022-12-10 17:04
The first version worked partially, but created other problems. This is solved with the second version and works on frontend and backend with the standard templates.
Unfortunately it is now my turn to find out, why it is not working with my template.
Background: I'm calling a list from the intro section of a details view with the content plugin. The list is displayed correct, but when I try to open the details view of one of the entries, the wrong entry is displayed...

**Comment by wezetel** [comment] 2022-12-10 19:21
Need to investigate further. Found out there are also problems with Cassiopeia. Seems to be related to SEF (my first impression). The correct entry is displayed when I remove the URL part before '/display/x/y'
I will report when my headache is gone and I find the time...

**Comment by skurvish** [comment] 2022-12-10 19:26
@wezetel Please open a new issue once you figure out what is happening and you identify it as a Fabrik issue. I am closing this one as fixed.

**Closed by skurvish** 2022-12-10 19:26 UTC
