### ISSUE TITLE
Access & Folder Element Plugins are not sizeable

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#233] opened 2022-08-19 13:02 UTC
Does not appear they ever were. Therefore they always spans the entire width of the container.

Should they be sizable like all other elements?

**Comment by joomlahenk** [comment] 2022-08-19 17:51
I did managed to fix that for access, if I remember. Will see what's changed. I am testing BS5 layouts for elements #228 and the first that appears is: 
Warning: Undefined property: stdClass::$span in /var/www/html/j4test/components/com_fabrik/layouts/form/fabrik-control-group.php on line 14
Warning: Undefined property: stdClass::$style in /var/www/html/j4test/components/com_fabrik/layouts/form/fabrik-control-group.php on line 30

Maybe you can set error reporting on maximum to see it also.

**Comment by skurvish** [comment] 2022-08-19 17:57
I fixed that in a commit about 30 minutes ago.

Sent from my amazing Pocophone
________________________________

**Comment by joomlahenk** [comment] 2022-08-19 18:06
Acces & Folder elements are sizeable here, they don't span the entire width. I can change the size by altering col-sm-5 to col-sm-3 or whatever.
I did a GH pull, so I have most recent version and copied all fabrik files over existing files in a local site. Then I do all tests on this local site.

**Comment by joomlahenk** [comment] 2022-08-19 18:09
OK, I didn't check the last commit yet. Will do now.

**Comment by joomlahenk** [comment] 2022-08-19 19:40
Tested again after #231 : 
Acces & Folder elements are still sizeable and ok.
There is an issue with birthday: set class="fabrikElement col-sm-6" and style="130px" does nothing, just remove it is. Then it's ok.
Not completely tested yet, need to test more

**Comment by skurvish** [comment] 2022-08-19 21:09
Where are you seeing the set class?

The reason for the style=130px;" is because without it the dropdowns and not the same size which is how they were in J3. Setting this size the 3 dropdowns are equal sizes.

**Comment by skurvish** [comment] 2022-08-19 21:17
With regards to access and folders. I do not see anywhere in the elements that you can set the size. In the admin interface the select is getting a col-sm-5 which it should nto be getting so I need to look into this further. In the front end this does not happen. 

I apologize, some of these elements I did not test in the admin, it is easier in the site side. I will do more testing tomorrow.

**Comment by joomlahenk** [comment] 2022-08-20 07:39
I simply use chrome browser to inspect elements. Then I go to the item I want to check and see all html and css. Then I change some of that to make it ok. Then I go to the code and try to find where to set it. Some is very hard to find, because it can be in any .php. js. or .xml file in any location with any not so logical filename. 

col-sm-3 is far to small to show all birthday columns and must be col-sm-6. If I skip style=130px, columns size automatically and they have no equal size as it should. 
The same is for access and folders.

I think the strategy should be to first make all plugins acceptable working in backend and after that update the frontend using its own template and css. Changes in the backend may also change frontend

**Comment by joomlahenk** [comment] 2022-08-20 10:19
OK, I did some more tests and investigations.
The problem is that some elements don't have a format setting and also have no bsClass, like the access and birthday elements. They should get a fixed bsClass or add the format setting. Therefore I added a format setting for the link element and birthday element. So the col-sm-3 in the birthday element was set by the format setting. You can change this in the element settings.
I think it's better the set a fixed format of col-sm-6 for the birthday element and remove the format setting. I didn't find out yet how to set a fixed format (bsClass). The style="130px" should be removed anyway.

You changed all col-md-* to col-sm-*, but not for the format setting in the element plugins. I still need to select col-md-*.
In default_group_labels_side.php you added <div class="row mb-3">, but class="row mb-3" does nothing for as far I can see. If I remove it, nothing changes. This is for many elements; I don't have all yet.
I think you should not calculate the width. The user can change this in the element format setting. Let's leave this as it was in J!3.

**Comment by joomlahenk** [comment] 2022-08-20 11:20
OK, forget what I said about  class="row mb-3". My error, it needs to be there.
In components\com_fabrik\models\element.php line 8314, I added a default in case an element plugin did not set bootstrap_class.
This was in col-md-*, but must now be col-sm-*. So any element plugin that did not set bootstrap_class will get this default size.

So I think if you find out how to set a fixed value for the bootstrap_class of element plugins that don't have it, it will solve several size issues.

**Comment by skurvish** [comment] 2022-08-20 11:22
Yes, I have spent all week working on understanding BS5 layouts. The changes I put in there are for a reason.

**Comment by skurvish** [comment] 2022-08-20 11:24
Without the width style I found no way to make the birthday dropdowns an equal size. Using pure BS5 sizing the dropdown will always set a width to the longest text option (up to the width of the containing column).

**Comment by skurvish** [comment] 2022-08-20 13:01
> So I think if you find out how to set a fixed value for the bootstrap_class of element plugins that don't have it, it will solve several size issues.

Setting a fixed size is going to break some custom layouts. better to add the size option into the element. Do you want me to do this or do you want to do it?

**Comment by joomlahenk** [comment] 2022-08-20 13:49
I don't understand why you want an equal size for the birthday dropdowns. I think you don't need a big size for the numbers 1..31. 130px makes the box so small that I can't see what's in the box. So that is not going to work in the backend. Did you try the birthday element in the BACKEND ?
I can add the same size option for an element as I already did for birthday and link element. These setting will now still be col-md-* and not col-sm-*

**Comment by skurvish** [comment] 2022-08-20 13:58
I tested the birthday element in the backend and in the frontend on both Cassiopia and Helix Ultimate. In all cases the dropdowns are equal size and perfectly visible. The birthday element has equally sized dropdowns on J3 which is why I went out of my way to make them so on J4.

**Comment by joomlahenk** [comment] 2022-08-20 14:28
Maybe a matter of taste?

Backend with style="130px":
![birthday-back-with](https://user-images.githubusercontent.com/40104328/185751108-9b0b032d-a297-4832-a7a5-a889278f767c.jpg)

Backend without style="130px":
![birthday-back-without](https://user-images.githubusercontent.com/40104328/185751205-d416cf83-0706-4669-82de-98b437565c81.jpg)

Frontend with style="130px":
![birthday-front-with](https://user-images.githubusercontent.com/40104328/185751235-e1796586-2bd5-42a5-a7e4-bff211045c4d.jpg)

Frontend without style="130px":
![birthday-front-without](https://user-images.githubusercontent.com/40104328/185751305-d58f0ef1-52d2-4949-be50-810f265d5d80.jpg)

**Comment by skurvish** [comment] 2022-08-20 14:30
Well if we don't care if it looks different than in J3 then fine, remove the width style.

**Comment by joomlahenk** [comment] 2022-08-20 14:53
I also found a solution for the elements that have no size set (access, folder, birthday, ...): use col-auto instead of col-sm-*

**Comment by skurvish** [comment] 2022-08-20 15:11
col-auto is going to size the element based on the longest option plus the size of the dropdown arrow if there is one, then reduce it to fit within the current (or remaining) viewspace. I believe people will want more control over the width so they can align elements on the form to their liking.

**Comment by joomlahenk** [comment] 2022-08-20 16:22
OK, I will add a field for size selection in the access and folder elements and maybe some others I find, that's very simple. This will be a new option then, it is not in J!3. Maybe this is even easier for most users.
In J!3 the size of these boxes is fixed 220px and is set in the isis css on the 'select' html element and could only be changed in css. Now we can do it in the element setting.
I would leave the default col-auto in for the elements that still have no size selection.

**Comment by trob** [comment] 2022-08-21 18:46
What about adding col-auto to the element's bootstrap layout classes. 
I even would like to set it as default.
Then you'll get the full available space no matter if you use labels-above/side/none, if you are switching your group to multi-column or changing the number of columns, if there's a child element in a different form template etc.

**Comment by skurvish** [comment] 2022-08-21 18:48
col-sm-12 will do the same thing.

**Comment by trob** [comment] 2022-08-21 18:52
No, it won't. The labels (-aside) already have col-sm-2 so you can set max col-sm-10 if you want the label aside and you must edit each single element if you decide to change your layout.

**Comment by skurvish** [comment] 2022-08-21 19:45
You are absolutely correct. I will add that option in first thing tomorrow and see fi I can figure out where all the defaults are.

**Comment by skurvish** [comment] 2022-08-21 21:46
Wait, I am incorrect. The algorithm that is used takes the value entered in the bootstrap class and normalizes it for the viewport that it is being inserted into. So, if the viewport is ms-10, the ms-12 bootstrap class would be normalized to ms-10. A bootstrap class of ms-6 would be normalized to ms-5.

Shouldn't that do what we want or do you really want an ms-auto?

**Comment by trob** [comment] 2022-08-22 06:19
Ok, I didn't realize that you modify the selected classes.

**Comment by trob** [comment] 2022-08-22 10:22
In the bootstrap class selection you changed all col-md to col-sm
but
1. in element's xml the default is still col-md-6 -> which is no existing value -> so element default becomes col-sm-1
2. all already existing elements will get col-sm-1, too, on save (you usually don't expect to get settings modified which you haven't touched)

I don't want to mix up your stylings etc.
But xml should also use col-sm

For Fabrik4 updates:
- at least mention that all old bootstrap classes are gone (span, col-md, input-block-level)
- and/or have a mapping table from old to new classes
- and/or have a script to modify the element params

In general: 
I think framework related stuff should be (as far as possible) only in (overridable) layouts or templates.
So I would put the bootstrap "labels-side" label classes into components\com_fabrik\layouts\element\fabrik-element-label.php
https://github.com/joomlahenk/fabrik/pull/243

**Comment by skurvish** [comment] 2022-08-22 11:03
I made a note of this change in the upgrade wiki document. All old styles are already mapped to the new ones, col-md, span, input-xx.

I will adjust the xml files.

**Comment by skurvish** [comment] 2022-08-22 11:41
All adjusted with PR #244 

i am going to take a stab at adjusting the sizes when an element is saved if it had an old md/span value in it.

**Comment by skurvish** [comment] 2022-08-22 13:53
OK, I have inserted logic to update the BS Class in the element when it is edited in PR #245 . So at this point old bs classes will be transposed on the fly by the layout, and whenever the user edits and saves the element in the admin the class will be updated.

**Comment by trob** [comment] 2022-08-22 14:01
Sounds great. So I think the "input-x" classes can be removed from the selection dropdown?

**Comment by skurvish** [comment] 2022-08-22 14:02
I would tend to leave them, for some people they may make more sense?

**Comment by trob** [comment] 2022-08-22 14:10
Ok, yes, maybe also useful as "general" classes in case of non-BS5-templates.

**Comment by skurvish** [comment] 2022-08-22 23:07
Can we close this now?

**Comment by trob** [comment] 2022-08-23 07:15
Closing (Can always be re-opened)

**Closed by trob** 2022-08-23 07:15 UTC
