### ISSUE TITLE
Alpha2 - ACL protected list shows in a corner before login

### ISSUE THREAD

**Issue by lcollong** [joomlahenk/fabrik#380] opened 2022-10-19 06:55 UTC
Using default everywhere. Simple list. ACL set to public for view but registred for edit/add.
When logged on : beahavior as expected.
Before login : the list shows up in the upper left corner. Looks like an unexpected module....
![Capture_after_login](https://user-images.githubusercontent.com/1845856/196618115-704043c5-82ec-4b6b-b694-70e3a58515c8.PNG)
![Capture_before_login](https://user-images.githubusercontent.com/1845856/196618158-026ba1de-701d-4e77-9b73-1327521d2226.PNG)
![Capture_list_setup](https://user-images.githubusercontent.com/1845856/196618188-c79b31a6-1d10-45cc-97ef-b55016acbea1.PNG)

**Comment by skurvish** [comment] 2022-10-19 10:08
Well that is bizzare. I can recreate it so will have a look.

**Comment by joomlahenk** [comment] 2022-10-19 10:17
Yes, I can reproduce this, does not happen in J!3. It happens when I set ACL for add records to Registered or higher (public and guest is ok). Other ACL does not matter. I have no other users then super user only and I am not logged in. If I log-in as super user all is ok. If I create a new user in the group Registered. I have the issue if ACL for add records is set to Super user.
So in fact the issue occurs when Add records is disabled. The screen is also split-up after the add record button.
Only the button should be disabled; not been added to the menu.

**Comment by skurvish** [comment] 2022-10-19 10:21
Ys, there is a problem with the form rendering. I am looking at it now.

**Comment by joomlahenk** [comment] 2022-10-19 10:22
Solved by correcting some <div> in ...\bootstrap\default_buttons.php

**Comment by joomlahenk** [comment] 2022-10-19 10:28
@skurvish : No need to look. Repaired already.

**Comment by skurvish** [comment] 2022-10-19 10:29
OK. I was just getting there.

**Comment by skurvish** [comment] 2022-10-19 10:34
I confirm that the problem is fixed with commit [52be578](https://github.com/skurvish/fabrik/commit/52be5781b8074dbdc36adf934f170265012f09a1) closing this.

**Closed by skurvish** 2022-10-19 10:34 UTC
