### ISSUE TITLE
[alpha2] frontend menu settings Extra Query String

### ISSUE THREAD

**Issue by raramuridesign** [joomlahenk/fabrik#354] opened 2022-10-16 14:49 UTC
Screenshot with explanation

Adding query strings directly to the URL does work.
/index.php/ccc/form/1?apps_contact___name=Joe%20Soap

But not using the menu query params.

![image](https://user-images.githubusercontent.com/902376/196042106-9e8180e5-f124-4527-8cc8-815e67d3ad04.png)

**Comment by trob** [comment] 2022-10-17 07:38
List menu ?Extra querystring' is working.
So I assume the issue is not applying to the input but fetching the default values.

**Comment by skurvish** [comment] 2022-10-24 12:21
I see where this is happening and am able to get the extra QS variables in, but as per the documentation the string is url encoded and for a field element the value placed in the field is the url encoded value, so "/? etc are encoded as they %xx values. Also, fabrik is using the urlencode function which converts spaces to plus signs. For example, if I use &tablename___name="My Name" what is actually placed into the field is %22My+Name%22

I can change the urlencode to use rawurlencode and the + becomes %20, but I am not sure this is correct at the end of the day.

How is this handled in F3?

**Comment by skurvish** [comment] 2022-10-24 13:19
Not sure how this ever worked but PR #412 should correct it.

**Comment by trob** [comment] 2022-10-25 12:45
Fixed with PR https://github.com/joomlahenk/fabrik/pull/412

**Closed by trob** 2022-10-25 12:45 UTC
