### ISSUE TITLE
Warning in pop-up form

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#455] opened 2022-10-29 12:08 UTC
**To Reproduce**
Open record from a list or module in a ajaxified link

**Expected behavior**
Clean pop-up form

**Actual behavior**
Error in top of form: Warning: Array to string conversion in /usr/www/users/prachta/dtc/libraries/fabrik/fabrik/Document/Renderer/Partial/HeadRenderer.php on line 248

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/5586423/198830527-f7ef3761-ab76-4313-97b0-c9312cd780ea.png)

**Additional context**

**Comment by skurvish** [comment] 2022-10-29 12:32
I am not seeing this. What elements do you have on the form?

**Comment by EricdeWaal** [comment] 2022-10-29 12:42
cascading dropdown, databasejoin, field, googlemap, internalid, jdate, link, testarea

**Comment by skurvish** [comment] 2022-10-29 12:44
Do you think you can narrow it down to a specific plugin? I have a list with internalid, jdate, yesno and I am not seeing this error.

I am debugging some googlemap stuff at the moment or I would do this myself.

**Comment by EricdeWaal** [comment] 2022-10-29 12:59
I tried them all, no success. And I see this error in all pop-up forms. It disappears when i use a non-ajaxified link to the form

**Comment by joomlahenk** [comment] 2022-10-29 13:29
See also issues #377 & #331

**Comment by skurvish** [comment] 2022-10-29 14:41
OK, I see it now. In the future please indicate whether the issue is on the front end or back end. This issue seems to only affect the back end.

**Comment by skurvish** [comment] 2022-10-29 14:58
Should be fixed in PR #459

**Comment by EricdeWaal** [comment] 2022-10-29 15:30
No, it's on the front-end too!

**Comment by skurvish** [comment] 2022-10-29 22:03
@EricdeWaal can you test with the changes in PR #459?

**Comment by EricdeWaal** [comment] 2022-10-31 13:48
I cannot find what was done PR #459?

**Comment by joomlahenk** [comment] 2022-10-31 14:09
Issue solved on my site

@EricdeWaal : In PR#459 the file libraries/fabrik/fabrik/Document/Renderer/Partial/HeadRenderer.php is updated.
You need to do a GitHup update to get this updated file and copy that to your site folder. Then check again if the issue is solved.

**Comment by EricdeWaal** [comment] 2022-10-31 14:37
I replace the php file only, and yes I can confirm this removes the error!

**Closed** 2022-10-31 15:33 UTC
Labels: Pending confirmation
