### ISSUE TITLE
Issue after applying PR #208

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#213] opened 2022-08-11 16:34 UTC
After install on a virgin J!4 I get a long list of database errors. (J!4 system->maintenance->database fabrik, hover on 'one problem'):
Table #__fabrik_cron has the wrong type or attributes for column 'created' with type datetime (From file 4.0.sql)
And so on for all datetime columns.

Like I said earlier:
I once tried to add the same default for a type timestamp column.
This was not accepted and generated an error. Then if I didn't add any default it is J! or mysql that automatically adds DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP and did not give the error.

So it seems this is also not accepted for type datetime. 
J! or mysql does not automatically adds it for type datetime

**Comment by skurvish** [comment] 2022-08-11 17:44
Are you possibly installing in something other than php8.1? My install and uninstall proceed successfully. The DATETIME change for null came as a result of php8.1.

**Comment by joomlahenk** [comment] 2022-08-11 20:29
Unclear why a database error can be caused by PHP8.1 / 8.0
I did try it twice, but will try several more times.

**Comment by skurvish** [comment] 2022-08-11 21:17
Please do. It installs perfectly on my system.

**Comment by joomlahenk** [comment] 2022-08-12 07:40
Tried again, same issue.
Joomla does not accept DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP for a type 'datetime'.
If you want to use that you should use type 'timestamp' without ant defaults, joomla will add DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP.

![system-maintenance](https://user-images.githubusercontent.com/40104328/184306838-405e48bc-259c-4d58-bba4-1adb7fd3aab7.jpg)

![fabrik-db-errors](https://user-images.githubusercontent.com/40104328/184307091-7e90b22e-9a13-48a0-b411-641be49875d1.jpg)

Hover over the red 'one problem' to see the db errors.
Why change the datetime defaults, we can leave it as it was (NULL). It never caused an issue, so why change it. Fabrik adds a datetime value for 'created' and 'modified'. As far as I can track back in my J!3 db's, fabrik has always stored the correct datetime value for 'created' and 'modified'.
Or did you encountered an issue with it?

**Comment by skurvish** [comment] 2022-08-12 12:26
Well, according to the mysql documentation the way I have it is correct: https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

I have tried executing the create table and the alter/modifies from the 4.0 sql directly in the mysql command line and the execute without error or warning, so I suspect this warning is coming from J! somewhere. I will dig into a little more.

**Comment by skurvish** [comment] 2022-08-12 14:48
OK, after further investigation the issue appears to be in Joomla. Joomla performs a database maintenance check when you land on the System or Database Maintenance pages in the admin. It goes through the SQL statements for the installed components and compares the settings for any sql update files against what the database currently shows for the table schema. All good stuff.

Mysql processed the update/alter with CURRENT_TIMESTAMP from the update sql correctly and does not error. So there is inherently nothing wrong with the sql as it is now.

Here is where we run into a problem. When J! performs its maintenance check on the tables it takes the attributes of each column and performs a sql SHOW COLUMNS for the table and uses WHERE statements as detailed in the sql file. The problem is that CURRENT_TIMESTAMP is actually stored in the database as current_timestamp() so the SHOW COLUMNS query returns no rows. This is what is causing the table errors you see.

I am not sure how this issue can be resolved as I am no sql expert. I have opened an issue on the J! Database Framework forum and see what they have to say.

For the time being, these error/warnings can be safely ignored.

**Comment by joomlahenk** [comment] 2022-08-12 16:58
Why not leave it as is was (default NULL), we have no issue with it. I don't like to just ignore these error/warnings, if it's not needed. This is not a real must, just make it work. Maybe you get a positive response from the J! team, but don't count on that.

**Comment by skurvish** [comment] 2022-08-12 19:53
Yeah, I am not holding my breath. I fixed the null problem so I will go ahead and revert these to default null. Hopefully all will be good.

**Comment by skurvish** [comment] 2022-08-19 10:32
This appears to be fixed and working. Closing.

**Closed by skurvish** 2022-08-19 10:32 UTC
Labels: High Priority
