### ISSUE TITLE
Table (re)styling is needed in all modals, pre-filter, joins, etc.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#158] opened 2022-07-26 18:07 UTC
Some are even difficult to work with. For most it's very hard to find where stying is done.

**Comment by skurvish** [comment] 2022-07-27 10:18
The modal sizing, at least for the modal popups, is done in javascript. I know where it is done but I haven't figured out how to solve it. I just noted the issue with plans to come back and fix it after I solved a couple of other items.

**Comment by joomlahenk** [comment] 2022-07-27 13:16
I am trying to do this for the list pre-filter and joins. I updated some, but all items are everywhere and nowhere; in the list model or js or .... They just can be anywhere or may be not defined

**Comment by joomlahenk** [comment] 2022-07-30 11:47
I was able to update the list pre-filter settings table for BS5. I could not update the list join tabel for BS5. This must be done in listform.js, but this js code is more complicated. If I change the selections to 'form-select-sm' as I did in the pre-filter, the 'id' fields no longer work.

**Comment by joomlahenk** [comment] 2022-08-02 13:41
I updates the join table for BS5 as far as possible right now. The only thing I can't fix is the form-select for 'From-column' and 'To-column', they have form-select, but when the content changes this is reverted back to inputbox.

**Comment by joomlahenk** [comment] 2022-08-02 15:03
Most of the modal sizing in done in fabrikmodalrepeat.js, not all of course (it's fabrik). I did give it a try, but it's made rather complicated in js. Maybe it's even easier to remove the form-select's for these modals. The modals are not usable as they are now.

**Comment by skurvish** [comment] 2022-08-02 17:02
let me take a crack at it. Check in any changes you have already made. As soon as I get the search filters fixed I will look at this.

**Comment by skurvish** [comment] 2022-08-05 15:33
So it appears to be a mootools issue. Fabrik uses mootools for all of its modal popups. During the rendering phase there are mootools functions for determining the window size for displaying the modal popups (these are in fabrikmodalrepeats.js). The problem is that boostrap resizes things on the fly and mootools doesn't know about it. This is particularly bothersome with the select lists. With the formselect class bootstrap resises the select at display time which happens after mootools has done its thing.

I can remove the formselect class from some of them but not all of them because the same form layouts are used elsewhere.

Converting the modals to bootstrap modals is probably the right thing to do but I expect this is going to be a big job. Alternatively I can create new fieldtypes for these that do not use the formselect class.

Anyway, I am still plugging away.

**Comment by joomlahenk** [comment] 2022-08-06 07:41
Yes, this is going to be a big job, it would be great if you can get it working.
Converting the modals to bootstrap modals is maybe something for later. If you can make the modals workable this will be good enough.

**Comment by skurvish** [comment] 2022-08-06 16:46
I have submitted PR #197 as a start to fixing this. 

Please test. Right now all I have fixed are the list pre-filters and element list for the list menu item. There may be other places I need to fix as well so when you find them let me know.

I also need to adjust the install to copy over this layout override. Will get on that once you guys are happy this is resolved.

**Comment by skurvish** [comment] 2022-08-06 17:02
I have modified the install manifest to copy over/delete this new layout override. I have not tested it yet. I will wait a bit until you 2 test the actual modals etc.

**Comment by joomlahenk** [comment] 2022-08-07 09:22
Tested, result:

todo: minify fabrikmodalrepeat.js

I put the override list.php file in: admin/templates/atum/html/layouts/joomla/form/field/

Everywhere I get: 
Warning: Constant FABRIK_JOOMLA_LISTFIELD_LAYOUT_OVERRIDE already defined in .../administrator/components/com_fabrik/layouts/joomla/form/field/list.php on line 10

So I need to set Error reporting to system default, then I test modals again:

modal ok on:
list->details->filters->elements
list->publishing->CSV->elements
filter pop-up (may need a little more styling)

modal not ok on:
list->details->layout->responsive-css still have form-select
list->publishing->oia->element-mapping still have form-select

list->view-data
displays class="input-append" on top
dark filter button => remove btn-secondary in components/com_fabrik/views/list/tmpl/bootstrap/default_buttons.php line 67

**Comment by skurvish** [comment] 2022-08-07 11:34
Thanks for that testing. I have made the changes and minified the js file in PR #200

**Comment by joomlahenk** [comment] 2022-08-07 11:51
Merged. Did you also look at the Warning?

**Comment by skurvish** [comment] 2022-08-07 12:20
Yes I did.

**Comment by joomlahenk** [comment] 2022-08-07 13:58
Looks real good. Maybe we can do some more styling later-on, but it's good enough now.
I didn't test ALL filter settings, there are many.
Think we can close this one.

**Comment by skurvish** [comment] 2022-08-07 15:17
@trob perhaps you can have a look before we close this. You use some different areas of the system than I or Henk do. When you are happy we can close this.

**Comment by trob** [comment] 2022-08-22 13:52
The pre-filter popup in fabrik list menu (I can't find the place at the moment) should set 
class="form-select-sm" for all dropdowns
At the moment it's "form-select" and the element dropdown is still "inputbox"

**Comment by skurvish** [comment] 2022-08-22 14:41
Fixed in PR #245

**Comment by skurvish** [comment] 2022-08-22 23:08
If you are both happy with this can we close this one?

**Comment by trob** [comment] 2022-08-23 07:23
The pre-filter popup in **Fabrik list menu** option needs still `class="form-select-sm" for all dropdowns
At the moment it's "form-select" and the element dropdown is still "inputbox"`
And it is throwing
![grafik](https://user-images.githubusercontent.com/1045355/186096293-950a897f-cad4-4009-bc34-f8681931b7c7.png)

**Comment by joomlahenk** [comment] 2022-08-23 08:05
@trob I can't replicate. Do you mean: menu->all-menu-items->the-created-list-menu-item->fabrik-list-options->pre-filters ?
All dropdowns are inputbox, because size is set to -9999. This is forced by the list.php override if I am right.  I don't get console errors.

**Comment by trob** [comment] 2022-08-23 09:27
`menu->all-menu-items->the-created-list-menu-item->fabrik-list-options->pre-filters`Yup. I get this
![grafik](https://user-images.githubusercontent.com/1045355/186121555-a5ad9314-90f8-442e-8ac8-69139d5782e9.png)

Ignore the JS error for now. It seems to be random, only one list menu showed it, now it is gone but each new pre-filter row in this menu item has 'undefined' text in the Value box as default. I'll open a new issue for this if necessary.

**Comment by skurvish** [comment] 2022-08-23 10:22
That shouldn't be too hard to fix. I'll have a go at it later today.

I have a suspicion the js error is as a result of changing the markup and perhaps dropping some of the classes. I will have a look at that as well.

**Comment by joomlahenk** [comment] 2022-08-23 10:31
Yes, you can change in into form-select-sm in the browser and I would like to have that set in code also. But, if I am right,  @skurvish needed to create an override to make the modal pop-up working and for that he needed to change form-select into inputbox. See ..\administrator\templates\atum\html\layouts\joomla\form\field\list.php

**Comment by joomlahenk** [comment] 2022-08-23 10:48
Well, just found out, if I change the override list.php in line 20: $buffer = str_replace("form-select", "form-select-sm inputbox", $buffer); we get all dropdowns like you (and I) wanted, except for the elements dropdown.
@skurvish : Can you clarify this?

**Comment by trob** [comment] 2022-08-23 10:50
The layout was "nearly" ok without the copied override file (just the form-select rendering "big" dropdowns, not splitted or broken as in the beginning), so do we need this a bit critical override at all?

**Comment by skurvish** [comment] 2022-08-23 11:46
The issue was that the same list rendering was happening for standard forms as for the modal popups. They both use the same field type in the fields xml files. In order to get the selects to render properly in the modal forms we needed to change the form-select to inputbox (although we could change it to form-select-sm instead perhaps) only for the forms that are rendered as modals. That is why the size=-9999 is added to the field xml so that the override knows which fields to change.

I will look at the elements dropdown.

**Comment by skurvish** [comment] 2022-08-23 12:01
I think I have it soreted now, try with PR #246

**Comment by joomlahenk** [comment] 2022-08-23 13:34
Great, working perfect here.

**Closed** 2022-09-26 16:36 UTC
Labels: help wanted, question
